### ISSUE TITLE
Revisar archivo docker/requirementsLr.txt

### ISSUE THREAD

**Issue by nontoa** [TCCD2022/TCCD2022#20]
Hola @Daniel19902 podrías por favor revisar el archivo docker/requirementsLr.txt, al parecer no seleccionaste los cambios y el archivo quedo con "<<<<<<< HEAD" y aparece error al ejecutar el docker-compose.

**Comment by Venustiano** [comment]
Gracias por la observacion

@Daniel19902 de hecho esto es urgente. Por favor, **arreglalo** y realiza el pull request. 

@nontoa Podrias aprobar y realizar el `merge pull request` una vez que este listo. En caso de que no pueda hacerlo yo.

**Comment by Daniel19902** [comment]
Si señor, por el momento no me encuentro en la casa apenas llegué corrigió
el archivo que pena por el inconveniente y una disculpa a mis compañeros no
suelo revisar este correo.

**Comment by nontoa** [comment]
@Daniel19902 Muchas gracias por el cambio. @Venustiano Ya se realizó el merge pull request, procedo a cerrar el issue.
